FROM openjdk:8u212-jre
MAINTAINER crystal 764471698@qq.com

COPY platform-gateway-2.0-RELEASE.jar /platform/platform-gateway-2.0-RELEASE.jar

ENTRYPOINT ["java", "-jar", "/platform/platform-gateway-2.0-RELEASE.jar"]