FROM openjdk:8u212-jre
MAINTAINER crystal 764471698@qq.com

COPY platform-admin-2.0-RELEASE.jar /platform/platform-admin-2.0-RELEASE.jar


ENTRYPOINT ["java", "-jar", "/platform/platform-admin-2.0-RELEASE.jar"]