FROM openjdk:8u252
MAINTAINER crystal 764471698@qq.com

COPY ./target/platform-server-statistics-2.0-RELEASE.jar /platform/platform-statistics-job-2.0-RELEASE.jar

ENTRYPOINT ["java", "-jar", "/platform/platform-server-statistics-2.0-RELEASE.jar"]